### ISSUE TITLE
Gem needs to be updated

### ISSUE THREAD

**Issue by pintergreg** [jyruzicka/plottr#1]
I think Ruby really lacks a good, usable plotting library and when I saw yours I immediately wanted to try it out. Installed the gem and tried to run the example from the readme, but I could not. After some debugging I found out that the gem 0.1.0 does not contains practically anything from your repo and that is the reason why I got this error:

```
irb(main):001:0> require "plottr"
=> true
irb(main):002:0> Plottr::Table
NameError: uninitialized constant Plottr::Table
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
```
After this, I think I needless to say that the example does not works (with the gem).

**Comment by jyruzicka** [comment]
Hi @pintergreg! The RubyGems [plottr](https://rubygems.org/gems/plottr) is, in fact, not even this gem - it's a [completely different gem](https://github.com/sstgithub/plottr) also called Plottr. This is a project that I was working on while I was learning R, and which I have since abandoned. I *was* planning on making it excellent, uploading it to rubygems, etc. etc., but then life got in the way (and also, I started doing data manipulation in R rather than ruby).

Sorry I can't help further. You're very welcome to strip the project of any useful code.
